[versions]
compose-plugin = "1.6.11"
junit = "4.13.2"
kotlin = "2.0.0"
kotlinCsv = "1.3.0"
sl4j = "1.7.30"
coroutines = "1.5.2"
aay-chart = "Beta-0.0.5"


[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
kotlin-csv = {module="com.github.doyaaaaaken:kotlin-csv-jvm", version.ref="kotlinCsv"}
sl4j = {module="org.slf4j:slf4j-simple", version.ref="sl4j"}
coroutines-core = {module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref="coroutines"}
chart-aay = {module="io.github.thechance101:chart", version.ref="aay-chart"}

[plugins]
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }